apiVersion: apps/v1
kind: Deployment
metadata:
  name: AIPublicationAutomation
  labels:
    app: AIPublicationAutomation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: AIPublicationAutomation
  template:
    metadata:
      labels:
        app: AIPublicationAutomation
    spec:
      containers:
        - name: AIPublicationAutomation
          image: "username/AIPublicationAutomation:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
