apiVersion: v1
kind: Service
metadata:
  name: AIPublicationAutomation
  labels:
    app: AIPublicationAutomation
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: AIPublicationAutomation