apiVersion: apps/v1
kind: Deployment
metadata:
  name: Library
  labels:
    app: Library
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Library
  template:
    metadata:
      labels:
        app: Library
    spec:
      containers:
        - name: Library
          image: "username/Library:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
