---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: AuthorManagement
  labels:
    app: AuthorManagement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: AuthorManagement
  template:
    metadata:
      labels:
        app: AuthorManagement
    spec:
      containers:
        - name: AuthorManagement
          image: username/AuthorManagement:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: SubscriptionManagement
  labels:
    app: SubscriptionManagement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: SubscriptionManagement
  template:
    metadata:
      labels:
        app: SubscriptionManagement
    spec:
      containers:
        - name: SubscriptionManagement
          image: username/SubscriptionManagement:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: Library
  labels:
    app: Library
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Library
  template:
    metadata:
      labels:
        app: Library
    spec:
      containers:
        - name: Library
          image: username/Library:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: AIPublicationAutomation
  labels:
    app: AIPublicationAutomation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: AIPublicationAutomation
  template:
    metadata:
      labels:
        app: AIPublicationAutomation
    spec:
      containers:
        - name: AIPublicationAutomation
          image: username/AIPublicationAutomation:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: PointManagement
  labels:
    app: PointManagement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: PointManagement
  template:
    metadata:
      labels:
        app: PointManagement
    spec:
      containers:
        - name: PointManagement
          image: username/PointManagement:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ManuscriptPublication
  labels:
    app: ManuscriptPublication
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ManuscriptPublication
  template:
    metadata:
      labels:
        app: ManuscriptPublication
    spec:
      containers:
        - name: ManuscriptPublication
          image: username/ManuscriptPublication:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: AuthorManagement
  labels:
    app: AuthorManagement
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: AuthorManagement


---


apiVersion: v1
kind: Service
metadata:
  name: SubscriptionManagement
  labels:
    app: SubscriptionManagement
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: SubscriptionManagement


---


apiVersion: v1
kind: Service
metadata:
  name: Library
  labels:
    app: Library
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: Library


---


apiVersion: v1
kind: Service
metadata:
  name: AIPublicationAutomation
  labels:
    app: AIPublicationAutomation
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: AIPublicationAutomation


---


apiVersion: v1
kind: Service
metadata:
  name: PointManagement
  labels:
    app: PointManagement
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: PointManagement


---


apiVersion: v1
kind: Service
metadata:
  name: ManuscriptPublication
  labels:
    app: ManuscriptPublication
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: ManuscriptPublication

