apiVersion: apps/v1
kind: Deployment
metadata:
  name: PointManagement
  labels:
    app: PointManagement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: PointManagement
  template:
    metadata:
      labels:
        app: PointManagement
    spec:
      containers:
        - name: PointManagement
          image: "username/PointManagement:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
